name: Deploy production

on:
  release:
    types: [published]

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  APP_NAME: relaybox
  CLUSTER_NAME: core-services
  SERVICE_NAME: session

jobs:
  deploy:
    name: deploy:prod
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          audience: sts.amazonaws.com
          role-to-assume: ${{ vars.AWS_CI_DEPLOYER_ROLE_ARN }}

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.AWS_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          npm ci
          npm run build
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Render task definition with environment variables and secrets
        env:
          IMAGE: ${{ steps.build-image.outputs.image }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          CRON_SCHEDULE_MINS: ${{ vars.CRON_SCHEDULE_MINS }}
          DB_HOST: ${{ vars.DB_HOST }}
          DB_NAME: ${{ vars.DB_NAME }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_PROXY_ENABLED: ${{ vars.DB_PROXY_ENABLED }}
          DB_IDLE_TIMEOUT_MS: ${{ vars.DB_IDLE_TIMEOUT_MS }}
          DB_MAX_CONNECTIONS: ${{ vars.DB_MAX_CONNECTIONS }}
          DB_USER: ${{ vars.DB_USER }}
          DB_TLS_DISABLED: ${{ vars.DB_TLS_DISABLED }}
          RABBIT_MQ_CONNECTION_STRING: ${{ vars.RABBIT_MQ_CONNECTION_STRING }}
          RABBIT_MQ_QUEUE_COUNT: ${{ vars.RABBIT_MQ_QUEUE_COUNT }}
          REDIS_HOST: ${{ vars.REDIS_HOST }}
          REDIS_PORT: ${{ vars.REDIS_PORT }}
          REDIS_AUTH_ARN: ${{ vars.REDIS_AUTH_ARN }}
          WS_IDLE_TIMEOUT_MS: ${{ vars.WS_IDLE_TIMEOUT_MS }}
          DB_PASSWORD_ARN: ${{ vars.DB_PASSWORD_ARN }}
          RDS_ROOT_CERTIFICATE_ARN: ${{ vars.RDS_ROOT_CERTIFICATE_ARN }}
        run: |
          envsubst < ecs/${{vars.STAGE}}/task-definition.json > ecs-task-definition.json

      - name: Register ECS task definition
        id: register-task
        run: |
          TASK_DEFINITION_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://ecs-task-definition.json \
            --region ${{ vars.AWS_REGION }} \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
          echo "task-definition-arn=$TASK_DEFINITION_ARN" >> $GITHUB_OUTPUT

      - name: Deploy Amazon ECS service
        run: |
          aws ecs update-service \
            --region ${{ vars.AWS_REGION }} \
            --cluster ${{env.APP_NAME}}-${{ env.CLUSTER_NAME }}-${{vars.STAGE}}-ecs-cluster-ECSCluster-9pkS9BJE3t40 \
            --service ${{env.APP_NAME}}-${{ env.SERVICE_NAME }}-${{vars.STAGE}}-ecs-service-ECSService-HcnXKEogkl4w \
            --task-definition ${{ steps.register-task.outputs.task-definition-arn }} \
            --force-new-deployment

  publish-docker-image:
    name: publish-docker-image
    runs-on: ubuntu-latest
    needs: deploy
    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT

      - name: Validate version extraction
        run: |
          if [ -z "${{ steps.get_version.outputs.version }}" ]; then
            echo "Error: Version could not be extracted from the tag."
            exit 1
          fi

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          echo "Building Docker image with version ${{ steps.get_version.outputs.version }}"
          docker build -t relaybox/session:latest -t relaybox/session:${{ steps.get_version.outputs.version }} .

      - name: Push Docker image
        run: |
          docker push relaybox/session:latest
          docker push relaybox/session:${{ steps.get_version.outputs.version }}

  update-package-version:
    name: update-package-version
    runs-on: ubuntu-latest
    needs: deploy
    permissions:
      contents: write
    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Update package version
        run: |
          VERSION=${{ github.ref_name }}
          npm version ${VERSION#v} --no-git-tag-version

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update package version [skip ci]'
          commit_author: GitHub Actions <actions@github.com>
          branch: main
