name: Deploy development

on:
  push:
    branches:
      - main
      - feature/20240919_workflow_refactor_v2

jobs:
  build-app:
    name: Build / Application
    uses: ./.github/workflows/build-application.yml

  build-push-ecr:
    name: Build Image / Push ECR
    uses: ./.github/workflows/build-push-ecr.yml
    needs: build-app
    with:
      environment: development
      service-name: session
    secrets: inherit

  deploy-ecs:
    name: Deploy ECS / Development
    uses: ./.github/workflows/deploy-ecs.yml
    needs: build-push-ecr
    with:
      environment: development
      ecr-image: ${{ needs.build-push-ecr.outputs.ecr_image }}
      cluster-name: core-services
      cluster-suffix: g8M6HWc0Cdph
      service-name: session
      service-suffix: nRbrd4FYxrs8
